(()=>{
  const cleanLabel=value=>String(value||'').replace(/[â€œâ€"]/g,'').split(/[Â·:]/)[0].trim().split(/\s+/).slice(0,3).join(' ').toUpperCase();
  const modeFor=scene=>{const text=`${scene.type||''} ${scene.title||''} ${scene.kicker||''}`.toLowerCase();if(/uncover|beneath|belief|story|layer|pattern/.test(text))return'layers';if(/scope|refer|boundary|therapy|safety|consent|trust/.test(text))return'boundary';if(/choice|ownership|decision|option|autonomy/.test(text))return'choice';if(/execute|action|accountab|commit|practice|experiment|review/.test(text))return'cycle';return'pathway'};
  const fallbacks={pathway:['R','O','U','X'],layers:['VISIBLE','MEANING','NEED','VALUE'],boundary:['NOTICE','PAUSE','REFER','SUPPORT'],choice:['FACT','OPTION','VALUE','CHOICE'],cycle:['INSIGHT','STEP','REVIEW','ADJUST']};
  const pathFor=mode=>mode==='cycle'?'M18 52 C35 5 65 5 82 52 C65 96 35 96 18 52':mode==='choice'?'M10 20 C32 20 34 52 50 52 M50 52 C66 52 68 20 90 20 M50 52 C66 52 68 84 90 84':'M8 52 C28 20 40 84 58 52 S78 20 92 52';
  function installGraphic(){const host=document.querySelector('.diagram-inner');if(!host||host.querySelector('.motion-graphic'))return;const title=document.querySelector('.title')?.textContent||'',kicker=document.querySelector('.kicker')?.textContent||'',body=[...document.querySelectorAll('.card b')].map(node=>node.textContent.trim()).slice(0,4),scene={title,kicker,body};const mode=modeFor(scene),labels=(body.length?body.map(cleanLabel):fallbacks[mode]).slice(0,4);while(labels.length<4)labels.push(fallbacks[mode][labels.length]);const route=pathFor(mode);const graphic=document.createElement('div');graphic.className='motion-graphic';graphic.dataset.mode=mode;graphic.setAttribute('aria-label','Narration-synchronized concept map');graphic.innerHTML=`<svg class="motion-path" viewBox="0 0 100 104" preserveAspectRatio="none" aria-hidden="true"><path d="${route}"></path><path class="motion-progress" pathLength="1" d="${route}"></path></svg><div class="motion-nodes">${labels.map((label,i)=>`<span class="motion-node" data-motion-node="${i}">${label}</span>`).join('')}</div><div class="motion-label">Follow the concept as it develops.<span class="motion-caption">Earlier ideas remain visible while the next idea arrives.</span></div>`;host.prepend(graphic)}
  function syncGraphic(active,scene){const graphic=document.querySelector('.motion-graphic');if(!graphic)return;graphic.classList.add('is-live');const nodes=[...graphic.querySelectorAll('.motion-node')];nodes.forEach((node,i)=>{node.classList.toggle('is-past',i<active);node.classList.toggle('is-current',i===active)});const progress=graphic.querySelector('.motion-progress');if(progress)progress.style.strokeDashoffset=String(Math.max(0,1-(active+1)/Math.max(1,nodes.length)));const label=graphic.querySelector('.motion-label');if(label&&scene.body?.[active])label.firstChild.textContent=scene.body[active]}
  const originalRender=window.render;let direction=0;window.render=function(...args){const result=originalRender.apply(this,args);direction+=1;document.getElementById('stage')?.classList.toggle('scene-forward',direction%2===0);document.getElementById('stage')?.classList.toggle('scene-back',direction%2===1);installGraphic();return result};
  const originalActivate=window.activateConcept;window.activateConcept=function(active,scene,...rest){const result=originalActivate.call(this,active,scene,...rest);syncGraphic(active,scene);return result};
})();

