(()=>{
  const profiles=[
    {test:/four-stage pathway|full courageous roux|roux map|framework in motion/i,model:'roux',labels:['RECOGNIZE','OPEN','UNCOVER','EXECUTE'],path:'M9 61 C25 61 27 31 42 31 S60 31 69 31 S78 61 92 61'},
    {test:/facts, stories, and feelings|fact.*story.*feeling|current reality/i,model:'lenses',labels:['FACT','STORY','FEELING'],path:'M12 46 C30 46 34 22 50 22 C66 22 70 46 88 46 M50 22 L50 72'},
    {test:/uncover|beneath the surface|competing commitments|protective pattern/i,model:'layers',labels:['VISIBLE','MEANING','PROTECTION','VALUE'],path:'M18 20 H82 M24 39 H76 M30 58 H70 M37 77 H63'},
    {test:/execute|action step|first roux map|inner checklist/i,model:'steps',labels:['INSIGHT','CHOICE','ACTION','REVIEW'],path:'M11 74 H30 V57 H50 V40 H70 V23 H90'},
    {test:/scope and referral|ethical referral|coaching.*not therapy|safety/i,model:'handoff',labels:['NOTICE','PAUSE','REFER','SUPPORT'],path:'M10 44 H39 M61 44 H90 M42 30 L58 44 L42 58'},
    {test:/accountability|missed commitment|follow.through/i,model:'cycle',labels:['COMMIT','ACT','REVIEW','ADJUST'],path:'M19 52 C19 18 81 18 81 52 C81 84 19 84 19 52'},
    {test:/coach owns the process|client ownership|client remains.*decision/i,model:'balance',labels:['PROCESS','STRUCTURE','VALUES','CHOICE'],path:'M50 16 V72 M18 31 H82 M18 31 L11 61 M18 31 L28 61 M82 31 L72 61 M82 31 L89 61'},
    {test:/trust|permission|emotional safety/i,model:'bridge',labels:['PACE','PERMISSION','CURIOSITY','TRUST'],path:'M8 66 C25 18 75 18 92 66 M8 66 H92'}
  ];
  const label=value=>String(value||'').replace(/[â€œâ€"]/g,'').split(/[Â·:]/)[0].trim().split(/\s+/).slice(0,3).join(' ').toUpperCase();
  function profileFor(scene){const text=`${scene.type||''} ${scene.title||''} ${scene.kicker||''} ${(scene.body||[]).join(' ')}`;return profiles.find(profile=>profile.test.test(text))||null}
  function shapes(profile){if(profile.model==='layers')return[20,39,58,77].map((y,i)=>`<line class="shape" data-shape="${i}" x1="${18+i*6}" y1="${y}" x2="${82-i*6}" y2="${y}"/>`).join('');if(profile.model==='steps')return[0,1,2,3].map((_,i)=>`<rect class="shape" data-shape="${i}" x="${11+i*20}" y="${62-i*17}" width="19" height="17" rx="3"/>`).join('');if(profile.model==='balance')return[0,1,2,3].map((_,i)=>`<circle class="shape" data-shape="${i}" cx="${i<2?18:82}" cy="${i%2?61:31}" r="6"/>`).join('');return profile.labels.map((_,i)=>`<circle class="shape" data-shape="${i}" cx="${10+i*(80/Math.max(1,profile.labels.length-1))}" cy="${profile.model==='cycle'?[52,24,52,78][i]:profile.model==='lenses'?[46,22,46][i]:44}" r="6"/>`).join('')}
  function install(scene){const profile=profileFor(scene),host=document.querySelector('.diagram-inner'),panel=document.querySelector('.diagram');if(!profile||!host||host.querySelector('.purpose-motion'))return null;panel?.classList.add('has-purpose-motion');const source=(scene.body||[]).slice(0,profile.labels.length).map(label),labels=profile.labels.map((fallback,i)=>source[i]||fallback);const graphic=document.createElement('div');graphic.className='purpose-motion';graphic.dataset.model=profile.model;graphic.setAttribute('aria-label',`${profile.model} concept animation synchronized to narration`);graphic.innerHTML=`<svg viewBox="0 0 100 90" preserveAspectRatio="none" aria-hidden="true"><path class="route" d="${profile.path}"></path><path class="route-live" pathLength="1" d="${profile.path}"></path>${shapes(profile)}</svg>${labels.map((text,i)=>`<span class="visual-label" data-visual-label="${i}">${text}</span>`).join('')}<div class="motion-explainer">${scene.title}</div>`;host.prepend(graphic);return graphic}
  function sync(active,scene){const profile=profileFor(scene);if(!profile)return;const graphic=document.querySelector('.purpose-motion')||install(scene);if(!graphic)return;graphic.classList.add('is-live');const labels=[...graphic.querySelectorAll('.visual-label')],shapes=[...graphic.querySelectorAll('.shape')];[...labels,...shapes].forEach(element=>{const i=Number(element.dataset.visualLabel??element.dataset.shape);element.classList.toggle('is-past',i<active);element.classList.toggle('is-current',i===active)});const route=graphic.querySelector('.route-live');if(route)route.style.strokeDashoffset=String(Math.max(0,1-(active+1)/Math.max(1,labels.length)));const explainer=graphic.querySelector('.motion-explainer');if(explainer&&scene.body?.[active])explainer.textContent=scene.body[active]}
  const originalActivate=window.activateConcept;window.activateConcept=function(active,scene,...rest){const result=originalActivate.call(this,active,scene,...rest);sync(active,scene);return result};
})();

